### ISSUE TITLE
Dedicated server unable to start while using Creo Lib

### ISSUE THREAD

**Issue by Oranamous** [jack-zisa/CreoLib#12]
Appears to be an issue related to attempting to register client commands while the client is not available.
Apologies for the rushed report, I have to go very soon.
If you need anything I'd be happy to provide what I can, here's [latest.log](https://github.com/jack-zisa/CreoLib/files/11778566/latest.log)

**Comment by jack-zisa** [comment]
No need to apologize, thanks for the report! I'll look into this later & hopefully will have it fixed by tonight.

**Comment by jack-zisa** [comment]
Should be good to go, I released a new version just now. When tested, I was able to run a server successfully. Let me know if the issue/another issue persists!

**Comment by maybebas** [comment]
I have the exact same error
I have `CreoLib-1.20.1-1.0.0-beta.25.jar` and `fabric-loader-0.14.22`

Here's my [latest.log](https://github.com/jack-zisa/CreoLib/files/13046485/latest.log)
