### ISSUE TITLE
 crashes because of creo lib ( critical injection error)

### ISSUE THREAD

**Issue by forgolotl** [jack-zisa/CreoLib#23]
https://mclo.gs/j879g6f without creolib it also crashes because i have a mod that depends on it (i have no idea which one)

**Comment by jack-zisa** [comment]
You are using the Forge mod loader, which CreoLib does not support. The mod [Wilder Wild](https://legacy.curseforge.com/minecraft/mc-mods/wilder-world) depends on this library but that is a Fabric mod. Make sure you are only using mods that are supported on the mod loader being used.
