### ISSUE TITLE
Add a way to use multinoise as a biome setting

### ISSUE THREAD

**Issue by Danjhop4** [jack-zisa/CreoLib#3]
When trying to make a datapack that changes to custom biome layout you have to use a world preset or a dimension that makes it hard to have more then one version normal and large biomes

**Comment by jack-zisa** [comment]
I'm not entirely sure what you are suggesting, could you explain it further?

**Comment by Danjhop4** [comment]
make setting to allow you to use multinoise as a sort of preset biome source since you can’t override the default one with world presets or you have to use dimensions were you are stuck with just one world type a shared setting for multinoise there is a setting that refers to hardcoded presets only in 1.19.4 and 1.20 but can’t use that for custom multinoise only default ones

**Comment by jack-zisa** [comment]
Are you saying that world presets cannot be applied to dimensions added by mods/datapacks?

If thats the case, I agree that would be a good thing to change although I'm not sure how difficult it would be to do.

But, after taking a look at [misode](https://misode.github.io/worldgen/world-preset/), it seems you can enter any dimension identifier into a world preset. I'm unable to test if a custom one would work so who knows? I'll keep your suggestion in mind though.

**Comment by jack-zisa** [comment]
Hi again. I got some help trying to understand what you were saying. It seems the issue you're suggesting is related to [MC-260949](https://bugs.mojang.com/browse/MC-260949), which is a confirmed issue by Mojang. It is considered an important bug, so it will likely be fixed in an upcoming update.

I'm going to close this issue.

**Comment by Danjhop4** [comment]
> Hi again. I got some help trying to understand what you were saying. It seems the issue you're suggesting is related to [MC-260949](https://bugs.mojang.com/browse/MC-260949), which is a confirmed issue by Mojang. It is considered an important bug, so it will likely be fixed in an upcoming update.
> 
> I'm going to close this issue.

I have not tried that lol

**Comment by Danjhop4** [comment]
> Hi again. I got some help trying to understand what you were saying. It seems the issue you're suggesting is related to [MC-260949](https://bugs.mojang.com/browse/MC-260949), which is a confirmed issue by Mojang. It is considered an important bug, so it will likely be fixed in an upcoming update.
> 
> I'm going to close this issue.

Seems only big datapack makers get there bugs confirmed
