### ISSUE TITLE
I only spam when forced if people are clearly being lazy

### ISSUE THREAD

**Issue by Danjhop4** [jack-zisa/CreoLib#5]
if give vaild reasons I am cool with that
Seems you have to be a big creator to have mojang even accept your bug no wonder misode as a helper and a creator gets there way to important 
json is hard 
Not going to make new issue but can you support snapshots

**Comment by jack-zisa** [comment]
I have no idea what you are talking about. Take a look at my mods, they aren't big. I've never written a bug report. Misode is not my 'helper', I've never even spoke directly to him.
Minecraft JSON is hard, you're right in that. I'm very sorry that you have been struggling with it, but you need to stop spamming worldgen devs for help when clearly you haven't been able to learn anything on your own. We aren't going to spend the time to help you anymore. You've proven that you, in fact, are the lazy one. In the time you've spent spamming every Miencraft worldgen creator on the face of this planet, you probably could've made something of your own that you could be proud of. It's unfortunate, really.

I am going to block you from this repository as I'm confident nothing I say will stop you from continuous spam. Very sorry, but you've done this to yourself.

**Comment by Danjhop5** [comment]
Hi

**Comment by Danjhop5** [comment]
> I have no idea what you are talking about. Take a look at my mods, they aren't big. I've never written a bug report. Misode is not my 'helper', I've never even spoke directly to him. Minecraft JSON is hard, you're right in that. I'm very sorry that you have been struggling with it, but you need to stop spamming worldgen devs for help when clearly you haven't been able to learn anything on your own. We aren't going to spend the time to help you anymore. You've proven that you, in fact, are the lazy one. In the time you've spent spamming every Miencraft worldgen creator on the face of this planet, you probably could've made something of your own that you could be proud of. It's unfortunate, really.
> 
> I am going to block you from this repository as I'm confident nothing I say will stop you from continuous spam. Very sorry, but you've done this to yourself.

I am back lol
